/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Codec configuration options */
export interface CodecOptions {
  codecName?: string
  bitRate?: number
  width?: number
  height?: number
  frameRate?: number
  sampleRate?: number
  channels?: number
  gopSize?: number
  maxBFrames?: number
  crf?: number
  preset?: string
  tune?: string
  profile?: string
  level?: number
}

/** Extract frames from video file as RGBA buffers */
export declare function extractFramesAsRgba(inputPath: string, maxFrames?: number | undefined | null): Array<FrameData>

/** Extract frames from video and save directly as images */
export declare function extractFramesToImages(inputPath: string, outputDir: string, maxFrames?: number | undefined | null, imageFormat?: string | undefined | null): Array<string>

/** Extract frames from video using v_frame */
export declare function extractFramesWithVFrame(inputPath: string, maxFrames?: number | undefined | null): Array<FrameData>

/** Filter configuration */
export interface FilterConfig {
  filterString: string
}

/** Media container format information */
export interface FormatInfo {
  name: string
  longName: string
  duration?: number
  bitRate?: number
  startTime?: number
  nbStreams: number
}

/** Extract frames as RGBA buffers */
export interface FrameData {
  frameNumber: number
  width: number
  height: number
  rgbaData: Array<number>
}

/**
 * Get media information from a file
 *
 * Uses av-format to read media files and extract metadata including
 * format information and stream details.
 */
export declare function getMediaInfo(path: string): MediaInfo

/** Get media info summary */
export declare function getMediaSummary(path: string): string

/**
 * Get supported codecs
 *
 * Returns a list of codecs supported by Rust-AV ecosystem.
 */
export declare function getSupportedCodecs(): Array<string>

/**
 * Get supported formats
 *
 * Returns a list of container formats supported by Rust-AV ecosystem.
 */
export declare function getSupportedFormats(): Array<string>

/**
 * Get supported pixel formats
 *
 * Returns a list of pixel formats supported by v_frame.
 */
export declare function getSupportedPixelFormats(): Array<string>

/**
 * Get supported sample formats
 *
 * Returns a list of audio sample formats supported by av-data.
 */
export declare function getSupportedSampleFormats(): Array<string>

/** Complete media information */
export interface MediaInfo {
  format: FormatInfo
  streams: Array<StreamInfo>
}

/** Media processing result */
export interface MediaProcessingResult {
  success: boolean
  message: string
  format?: string
  codec?: string
}

/** Progress callback data */
export interface ProgressData {
  currentTime: number
  totalTime: number
  percentage: number
  fps?: number
  bitRate?: number
  size: number
}

/** Save frames as image files */
export declare function saveFramesAsImages(frames: Array<FrameData>, options: SaveFramesOptions): Array<string>

/** Options for saving frames as images */
export interface SaveFramesOptions {
  /** Output directory for images */
  outputDir: string
  /** Image format (png, jpg, bmp, etc.) */
  imageFormat?: string
  /** Prefix for image filenames */
  filenamePrefix?: string
  /** Number of digits for frame numbering (e.g., 4 = frame_0001.png) */
  frameNumberDigits?: number
}

/** Media stream information */
export interface StreamInfo {
  index: number
  codecType: string
  codecName: string
  bitRate?: number
  width?: number
  height?: number
  frameRate?: number
  sampleRate?: number
  channels?: number
  duration?: number
}

/**
 * Transcode media file
 *
 * Performs actual transcoding using av-format, av-data, and v_frame crates.
 * This includes decoding input frames, applying filters, and encoding to output format.
 */
export declare function transcode(options: TranscodeOptions): void

/** Transcoding options */
export interface TranscodeOptions {
  inputPath: string
  outputPath: string
  videoCodec?: CodecOptions
  audioCodec?: CodecOptions
  videoFilter?: FilterConfig
  audioFilter?: FilterConfig
  format?: string
  startTime?: number
  duration?: number
  seekTo?: number
}

/**
 * Transform media file from one format to another
 *
 * Converts a media file from its current format to a target format.
 * Uses actual transcoding implementation with proper format handling.
 */
export declare function transformFormat(inputPath: string, outputPath: string): void

/** Validate a media file and return validation result */
export declare function validateFile(filePath: string): ValidationResult

/** Validate media file */
export declare function validateMediaFile(path: string): MediaProcessingResult

/** Validation result for a media file */
export interface ValidationResult {
  isValid: boolean
  format: string
  duration?: number
  width?: number
  height?: number
  codec?: string
  frameCount?: number
  errors: Array<string>
  warnings: Array<string>
}
