/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class GstKit {
  constructor()
  setPipeline(pipelineString: string): void
  play(): void
  pause(): void
  stop(): void
  pullSample(elementName: string): Buffer | null
  getState(): string
}
