/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Main GStreamer wrapper class for Node.js
 *
 * `GstKit` provides a high-level interface for creating and controlling
 * GStreamer pipelines. It supports playback control, data extraction,
 * and property manipulation.
 */
export declare class GstKit {
  /**
   * Creates a new `GstKit` instance and initializes GStreamer
   *
   * # Returns
   * * `Result<Self>` - A new GstKit instance or an error if initialization fails
   *
   * # Example
   * ```javascript
   * const kit = new GstKit();
   * ```
   */
  constructor()
  /**
   * Sets up a GStreamer pipeline from a launch string
   *
   * # Arguments
   * * `pipeline_string` - A valid GStreamer pipeline description
   *
   * # Example
   * ```javascript
   * kit.setPipeline("videotestsrc ! video/x-raw,format=RGBA ! appsink name=sink");
   * ```
   */
  setPipeline(pipelineString: string): void
  /**
   * Sets up a callback for pipeline events
   *
   * # Arguments
   * * `callback` - A JavaScript function to call when pipeline events occur
   *
   * # Example
   * ```javascript
   * kit.onEvent((event) => {
   *   console.log("Event:", event.eventType, event.message);
   * });
   * ```
   */
  onEvent(callback: (arg?: unknown) => unknown): void
  /**
   * Sets up a callback for frame events from AppSink elements
   *
   * # Arguments
   * * `callback` - A JavaScript function to call when frames are available
   *
   * # Example
   * ```javascript
   * kit.onFrame((frame) => {
   *   console.log("Frame from", frame.sinkName, "size:", frame.data.length);
   * });
   * ```
   */
  onFrame(callback: (arg?: unknown) => unknown): void
  /**
   * Starts emitting frames from all AppSink elements in the pipeline
   *
   * # Arguments
   * * `sink_names` - Optional list of sink names to emit frames from. If empty, emits from all AppSinks.
   *
   * # Example
   * ```javascript
   * // Emit frames from all sinks
   * kit.startFrameEmission();
   *
   * // Emit frames from specific sink
   * kit.startFrameEmission(["mysink"]);
   * ```
   */
  startFrameEmission(sinkNames?: Array<string> | undefined | null): void
  /**
   * Stops emitting frames from AppSink elements
   *
   * # Example
   * ```javascript
   * kit.stopFrameEmission();
   * ```
   */
  stopFrameEmission(): void
  /**
   * Starts monitoring the pipeline bus for events
   *
   * This will call the event callback for various pipeline events:
   * - "eos": End of stream
   * - "error": Pipeline error
   * - "warning": Pipeline warning
   * - "state-changed": Pipeline state changed
   * - "element": Element message
   *
   * # Example
   * ```javascript
   * kit.startBusMonitoring();
   * ```
   */
  startBusMonitoring(): void
  /**
   * Starts playback of the pipeline
   *
   * # Example
   * ```javascript
   * kit.play();
   * ```
   */
  play(): void
  /**
   * Pauses the pipeline
   *
   * # Example
   * ```javascript
   * kit.pause();
   * ```
   */
  pause(): void
  /**
   * Stops the pipeline and sets it to NULL state
   *
   * # Example
   * ```javascript
   * kit.stop();
   * ```
   */
  stop(): void
  /**
   * Pulls a sample from a named AppSink element with a configurable timeout
   *
   * # Arguments
   * * `element_name` - The name of the AppSink element
   * * `timeout_ms` - Timeout in milliseconds (default: 100ms, use 0 for non-blocking)
   *
   * # Returns
   * * `Result<Option<Buffer>>` - A Buffer containing the sample data, or null if no sample is available
   *
   * # Example
   * ```javascript
   * const frame = kit.pullSample("mysink", 100);
   * if (frame) {
   *   console.log("Got frame of size:", frame.length);
   * }
   * ```
   */
  pullSample(elementName: string, timeoutMs?: number | undefined): Buffer | null
  /**
   * Pushes a buffer to a named AppSrc element
   *
   * # Arguments
   * * `element_name` - The name of the AppSrc element
   * * `data` - The data to push as a Buffer
   *
   * # Example
   * ```javascript
   * kit.pushSample("mysrc", Buffer.from([0, 1, 2, 3]));
   * ```
   */
  pushSample(elementName: string, data: Buffer): void
  /**
   * Returns the current state of the pipeline
   *
   * # Returns
   * * `Result<String>` - The current state as a string ("Playing", "Paused", "Null", "Ready")
   *
   * # Example
   * ```javascript
   * const state = kit.getState();
   * console.log("Current state:", state);
   * ```
   */
  getState(): string
  /**
   * Returns the current position of the pipeline in nanoseconds
   *
   * # Returns
   * * `Result<i64>` - Current position in nanoseconds
   *
   * # Example
   * ```javascript
   * const position = kit.getPosition();
   * console.log("Position (ns):", position);
   * ```
   */
  getPosition(): number
  /**
   * Returns the duration of the pipeline in nanoseconds
   *
   * # Returns
   * * `Result<i64>` - Duration in nanoseconds, or -1 if unknown
   *
   * # Example
   * ```javascript
   * const duration = kit.getDuration();
   * console.log("Duration (ns):", duration);
   * ```
   */
  getDuration(): number
  /**
   * Seeks to a specific position in the pipeline
   *
   * # Arguments
   * * `position_ns` - Position to seek to in nanoseconds
   *
   * # Example
   * ```javascript
   * // Seek to 5 seconds (5 * 1_000_000_000 nanoseconds)
   * kit.seek(5_000_000_000);
   * ```
   */
  seek(positionNs: number): void
  /**
   * Sets a property on a named element in the pipeline
   *
   * # Arguments
   * * `element_name` - The name of the element
   * * `property_name` - The name of the property
   * * `value` - The value to set (as a string)
   *
   * # Example
   * ```javascript
   * kit.setProperty("mysrc", "is-live", "true");
   * ```
   */
  setProperty(elementName: string, propertyName: string, value: string): void
  /**
   * Gets a property value from a named element in the pipeline
   *
   * # Arguments
   * * `element_name` - The name of the element
   * * `property_name` - The name of the property
   *
   * # Returns
   * * `Result<String>` - The property value as a string
   *
   * # Example
   * ```javascript
   * const value = kit.getProperty("mysrc", "is-live");
   * console.log("Property value:", value);
   * ```
   */
  getProperty(elementName: string, propertyName: string): string
  /**
   * Returns a list of all element names in the pipeline
   *
   * # Returns
   * * `Result<Vec<String>>` - Array of element names
   *
   * # Example
   * ```javascript
   * const elements = kit.getElements();
   * console.log("Elements:", elements);
   * ```
   */
  getElements(): Array<string>
  /**
   * Checks if the pipeline has been initialized
   *
   * # Returns
   * * `bool` - true if pipeline is initialized, false otherwise
   *
   * # Example
   * ```javascript
   * if (kit.isInitialized()) {
   *   console.log("Pipeline is ready");
   * }
   * ```
   */
  isInitialized(): boolean
  /**
   * Cleans up and releases the pipeline
   *
   * This method stops the pipeline and releases all resources.
   * After calling this, you must call `setPipeline` again to use the kit.
   *
   * # Example
   * ```javascript
   * kit.cleanup();
   * ```
   */
  cleanup(): void
}

/** Frame data emitted from AppSink */
export interface FrameData {
  /** The frame data as a buffer */
  data: Buffer
  /** The name of the sink element */
  sinkName: string
  /** Timestamp of the frame in nanoseconds */
  timestamp: number
}

/** Event types that can be emitted by the pipeline */
export interface PipelineEvent {
  /** The type of event */
  eventType: string
  /** Optional message associated with the event */
  message?: string
  /** Optional error code (for error events) */
  errorCode?: number
}
